config/routes.rb
SinglyRailsSkeleton::Application.routes.draw do
  devise_for :people

  resources :projects

  resources :people

  #match "auth/:service"          => "auth#service"
  match "auth/:service/connect"   => "auth#connect"
  match "auth/:provider/callback" => "auth#callback"
  match "logout"                  => "auth#logout"
  root :to                        => "default#home"
end

app/models/event.rb
class Event 
  
  include Mongoid::Document
  include Mongoid::Timestamps
  
  field :name
  field :shared_event_id, type: Integer
  field :description
  field :when_occurred, type: DateTime
  field :source
  field :type
  field :visibility

  belongs_to :person
  
  embedded_in :project
  attr_protected :project_id

  embeds_many :resources  
end

app/models/person.rb
require 'devise'

class Person

  include Mongoid::Document
  include Mongoid::Timestamps
  
  field :firstname
  field :lastname
  field :picture_url
  field :bio
  field :singly_token
  
  field :email, :default => ""
  field :encrypted_password, :default => ""
  
  ## Recoverable
  field :reset_password_token
  field :reset_password_sent_at, :type => DateTime

  ## Rememberable
  field :remember_created_at, :type => DateTime

  ## Trackable
  field :sign_in_count, :type => Integer, :default => 0
  field :current_sign_in_at, :type => DateTime
  field :last_sign_in_at, :type => DateTime
  field :current_sign_in_ip
  field :last_sign_in_ip

  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  
  
  # Setup accessible (or protected) attributes for your model
#  attr_accessible :email, :password, :password_confirmation, :remember_me, :singly_token
#  attr_accessible :bio, :firstname, :id, :lastname, :picture_url
  
  has_and_belongs_to_many :projects
  embeds_many :services

end

app/models/project.rb
class Project

  include Mongoid::Document
  include Mongoid::Timestamps

  field :name
  field :tagline
  field :description
  field :color
  field :path
  field :service_aliases, type: Hash
  
  embeds_many :events

  has_and_belongs_to_many :people  
end

app/models/resource.rb
class Resource
  
  include Mongoid::Document
  include Mongoid::Timestamps

  field :name
  field :image_url
  field :type, type: Integer
  field :source
  field :description

  embedded_in :event
  attr_protected :event_id

end

app/models/service.rb
class Service 

  include Mongoid::Document
  include Mongoid::Timestamps
  
  field :service_name
  field :connect_count, type: Integer, default: 0

  embedded_in :person
  attr_protected :person_id
    
end

app/models/service_project.rb
class ServiceProject

  include Mongoid::Document
  include Mongoid::Timestamps

  # field :service_id
  # field :project_id
  field :project_alias
  
  embedded_in :project
  belongs_to :service
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/auth_controller.rb
require "httparty"

class AuthController < ApplicationController

  SINGLY_API_BASE = "https://api.singly.com"
  
  before_filter :authenticate_person!

  def connect
    session[:service] = params[:service]
    redirect_to "/auth/singly?service=#{params[:service]}"
  end

  def callback
    auth = request.env["omniauth.auth"]
    session[:access_token] = auth.credentials.token
    current_person.singly_token = auth.credentials.token
    current_person.save
    redirect_to "/"
  end
  
  def logout
    session.clear
    redirect_to "/"
  end
end

app/controllers/default_controller.rb
require "httparty"

class DefaultController < ApplicationController

before_filter :authenticate_person!

  def home
    if access_token
      @profiles = get_singly(profiles_url)
      @github_events = get_singly(github_events_url)
    end
  end

private

  def access_token
    session[:access_token]
  end

  SINGLY_API_BASE = "https://api.singly.com"

  def profiles_url
    "#{SINGLY_API_BASE}/profiles"
  end

  def github_events_url
    "#{SINGLY_API_BASE}/v0/services/github/events"
  end

  def get_singly(url)
    HTTParty.get(url,
        :query => {:access_token => access_token}
      ).parsed_response
  end

end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  # GET /people
  # GET /people.json
  def index
    @people = Person.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @people }
    end
  end

  # GET /people/1
  # GET /people/1.json
  def show
    @person = Person.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @person }
    end
  end

  # GET /people/new
  # GET /people/new.json
  def new
    @person = Person.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @person }
    end
  end

  # GET /people/1/edit
  def edit
    @person = Person.find(params[:id])
  end

  # POST /people
  # POST /people.json
  def create
    @person = Person.new(params[:person])

    respond_to do |format|
      if @person.save
        format.html { redirect_to @person, notice: 'Person was successfully created.' }
        format.json { render json: @person, status: :created, location: @person }
      else
        format.html { render action: "new" }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /people/1
  # PUT /people/1.json
  def update
    @person = Person.find(params[:id])

    respond_to do |format|
      if @person.update_attributes(params[:person])
        format.html { redirect_to @person, notice: 'Person was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /people/1
  # DELETE /people/1.json
  def destroy
    @person = Person.find(params[:id])
    @person.destroy

    respond_to do |format|
      format.html { redirect_to people_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  # GET /projects
  # GET /projects.json
  def index
    @projects = Project.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @projects }
    end
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
    @project = Project.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @project }
    end
  end

  # GET /projects/new
  # GET /projects/new.json
  def new
    @project = Project.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @project }
    end
  end

  # GET /projects/1/edit
  def edit
    @project = Project.find(params[:id])
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(params[:project])

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render json: @project, status: :created, location: @project }
      else
        format.html { render action: "new" }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /projects/1
  # PUT /projects/1.json
  def update
    @project = Project.find(params[:id])

    respond_to do |format|
      if @project.update_attributes(params[:project])
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project = Project.find(params[:id])
    @project.destroy

    respond_to do |format|
      format.html { redirect_to projects_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/auth_helper.rb
module AuthHelper
end

app/helpers/default_helper.rb
module DefaultHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/default/home.html.haml
%h1 Singly OAuth Example
%h2
  - if @profiles
    Nice to see you again!
  - else
    Please connect a service
- if session[:access_token]
  %p
    Your access token is
    %input{:type => :text, :value => session[:access_token], :readonly => :readonly}
    %a(href="/logout") Log out
%ul
  - %w[facebook twitter gmail github].each do |service|
    %li
      = service.capitalize
      - if @profiles && @profiles[service]
        is connected as
        = @profiles[service]
      - else
        is not connected.
        %a(href="/auth/#{service}/connect") Connect

- if @github_events
  - @github_events.each do |event|
    = debug(event)
    / %dt
    /   = key
    / %dd
    /   = value
    

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Singly Rails Skeleton
    = stylesheet_link_tag    "application", :media => "all"
    = javascript_include_tag "application"
    = csrf_meta_tags
  %body
    = yield
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

app/views/people/_form.html.erb
<%= form_for(@person) do |f| %>
  <% if @person.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@person.errors.count, "error") %> prohibited this person from being saved:</h2>

      <ul>
      <% @person.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :id %><br />
    <%= f.number_field :id %>
  </div>
  <div class="field">
    <%= f.label :firstname %><br />
    <%= f.text_field :firstname %>
  </div>
  <div class="field">
    <%= f.label :lastname %><br />
    <%= f.text_field :lastname %>
  </div>
  <div class="field">
    <%= f.label :picture_url %><br />
    <%= f.text_field :picture_url %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :bio %><br />
    <%= f.text_field :bio %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/people/edit.html.erb
<h1>Editing person</h1>

<%= render 'form' %>

<%= link_to 'Show', @person %> |
<%= link_to 'Back', people_path %>

app/views/people/index.html.erb
<h1>Listing people</h1>

<table>
  <tr>
    <th>Id</th>
    <th>Firstname</th>
    <th>Lastname</th>
    <th>Picture url</th>
    <th>Email</th>
    <th>Bio</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @people.each do |person| %>
  <tr>
    <td><%= person.id %></td>
    <td><%= person.firstname %></td>
    <td><%= person.lastname %></td>
    <td><%= person.picture_url %></td>
    <td><%= person.email %></td>
    <td><%= person.bio %></td>
    <td><%= link_to 'Show', person %></td>
    <td><%= link_to 'Edit', edit_person_path(person) %></td>
    <td><%= link_to 'Destroy', person, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Person', new_person_path %>

app/views/people/new.html.erb
<h1>New person</h1>

<%= render 'form' %>

<%= link_to 'Back', people_path %>

app/views/people/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Id:</b>
  <%= @person.id %>
</p>

<p>
  <b>Firstname:</b>
  <%= @person.firstname %>
</p>

<p>
  <b>Lastname:</b>
  <%= @person.lastname %>
</p>

<p>
  <b>Picture url:</b>
  <%= @person.picture_url %>
</p>

<p>
  <b>Email:</b>
  <%= @person.email %>
</p>

<p>
  <b>Bio:</b>
  <%= @person.bio %>
</p>


<%= link_to 'Edit', edit_person_path(@person) %> |
<%= link_to 'Back', people_path %>

app/views/projects/_form.html.erb
<%= form_for(@project) do |f| %>
  <% if @project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% @project.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :id %><br />
    <%= f.number_field :id %>
  </div>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :tagline %><br />
    <%= f.text_field :tagline %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :color %><br />
    <%= f.text_field :color %>
  </div>
  <div class="field">
    <%= f.label :path %><br />
    <%= f.text_field :path %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/projects/edit.html.erb
<h1>Editing project</h1>

<%= render 'form' %>

<%= link_to 'Show', @project %> |
<%= link_to 'Back', projects_path %>

app/views/projects/index.html.erb
<h1>Listing projects</h1>

<table>
  <tr>
    <th>Id</th>
    <th>Name</th>
    <th>Tagline</th>
    <th>Description</th>
    <th>Color</th>
    <th>Path</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @projects.each do |project| %>
  <tr>
    <td><%= project.id %></td>
    <td><%= project.name %></td>
    <td><%= project.tagline %></td>
    <td><%= project.description %></td>
    <td><%= project.color %></td>
    <td><%= project.path %></td>
    <td><%= link_to 'Show', project %></td>
    <td><%= link_to 'Edit', edit_project_path(project) %></td>
    <td><%= link_to 'Destroy', project, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Project', new_project_path %>

app/views/projects/new.html.erb
<h1>New project</h1>

<%= render 'form' %>

<%= link_to 'Back', projects_path %>

app/views/projects/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Id:</b>
  <%= @project.id %>
</p>

<p>
  <b>Name:</b>
  <%= @project.name %>
</p>

<p>
  <b>Tagline:</b>
  <%= @project.tagline %>
</p>

<p>
  <b>Description:</b>
  <%= @project.description %>
</p>

<p>
  <b>Color:</b>
  <%= @project.color %>
</p>

<p>
  <b>Path:</b>
  <%= @project.path %>
</p>


<%= link_to 'Edit', edit_project_path(@project) %> |
<%= link_to 'Back', projects_path %>